dist: trusty
sudo: true
language: c
services:
  - docker
addons:
  apt:
    packages:
    - ccache
before_install:
- ssh-keyscan -H firehol.org >> ~/.ssh/known_hosts
before_script:
- ./setup.sh
script:
- for i in build-*.sh; do ./$i || exit 1; done
after_success:
- "(cd output/packages && for i in *; do md5sum -b $i > ../checksums/$i.md5; done)"
- cat output/checksums/*.md5
deploy:
  provider: releases
  api_key:
     secure: FfRAom/470wvwHuNb891EcXZnlsKvFVtG5BuCc2YunYkgfHr/eQd8aOx6pMSY1t7US1E1HRNq0Oq+BG/Aqq9sxjOXuG2965CJISlCLNpRsoyymEs9G3hYX0PDgS9OY/+ax+grPUyiSSKpNl+mnEeLXC1KwiP+mTetOHCmiwJWjp2hmmHY3Cwyr2ZBip3jlG5ANDa1o/0k5EI6f0LPFNKcNDEI1yhIEERsCr9cWIeFmaAjMYHyaaTzKFFvMGKjbGW3yinfRi33FtN7SOYIupjd6Jf9Bi8GZB13NANO0iZRqdaajhf6ymgSpWkFOENqjZ9niXoNkWzgawMNCu69LgbTvqolQn8tRMiulmLpBrwYgR4hZJ1oGH4rJ/aJqVPYtH/uSIt9Kdi3pwGo1vr5fF9J0bqpC1bY+mitVbJ9W9DX8eAgQ5evw5sRA4Sf4fDZXDx/2pup8XEEYngYV6/Y/pCfMR7BwJlaHGcooh/NiHKEPUohsD+u8GM1mCrbDhwhi56SvJGoAjaAWDmIdyWkCTPQ9CKEQKz+skZWoTP++lJCrPaXIRm+3Fjc+NZYn/kdk5HZdy+jItvaihTJMxUl/aY9PFVtIIlJFKdb2o04s9GH+6d3bPUWCST57IwFP5fr0bSh7A1YH8UPrvYJBiFUOByF/TTF/jBI69SuGVGZzdKwUk=
  skip_cleanup: true
  file_glob: true
  file: "output/*/*.*"
  on:
    repo: firehol/packages
    tags: true
