dist: trusty
sudo: true
language: c
services:
  - docker
addons:
  apt:
    packages:
    - ccache
before_install:
- ssh-keyscan -H firehol.org >> ~/.ssh/known_hosts
before_script:
- ./setup.sh
script:
- for i in build-*.sh; do ./$i || exit 1; done
after_success:
- "(cd output/packages && for i in *; do md5sum -b $i > ../checksums/$i.md5; done)"
- cat output/checksums/*.md5
deploy:
  provider: releases
  api_key:
    secure: f4m29mw74sdPDjE83w1ldA2xHlaHLZVHVnnVmAk4Iv1IM+VmtWMParDsQZVOCG24nsFCcNwuz9ykiqqkou/DCzB0Dymo+riz/swkOce0OyKcCYykjrFLSYIYwEb2gjwHFQH3oOnv1/c4FqsOzCuu1pC5cISCvObF1M03umUe6MrVpCsAfF4Vo/WYgiB3ilKusfYVIYcLRIwnjDeaxZeGTZFlott1Wpdm83ujISzjifiOVHLXL7cr0qa8xxXCMqVgBbg11p5tQsdY3dWktc28RSoZolqg2ez5W8JxsFDpWa0TGjw1fxxFu+ekmux9bAs6jGg+WmfNyhLXH6PC38h8ATvF27F1QhMLd9npqonrBzyAAqvNYMyuKL/P5l1O00ZdVN19tV3M1rjNJ41oAV+h1HmEcOARRF7P3N4b9O9gJZgqxWZLu9Tn4sQuxPT4lyqEB6ksPcyaj0PKjU3lZp3ucQ0v2FsjSvuYJIj40OgxzQesh3AkxZOgCW3GlnmNuT6zRpcJca93UqKWR8UueftKDZQCMwEzFiND8SRScqOscgHkFmX15rB4vX+NH0pfjXDtzio1MYE91wfWraOgwA793XFaJ+tFkToXwP3/N3ovR8dyadYRuCVBxvW9f2z/9NdFGA060xU2ypyPJjOV/+WkDu5pIrkWUoJnnlO2mSan1pM=
  skip_cleanup: true
  file_glob: true
  file: "output/*/*.*"
  on:
    repo: firehol/packages
    tags: true
